server:
  port: 9080


spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/goldcat?useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: goldcat
      password: goldcat

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
mapper:
  not-empty: true

eden:
  msutils:
    boot:
      base-package: com.eden.finance.goldcat
      transaction:
        enabled: true
        cut-layer: controller
    cache:
      type: caffeine
logging:
  level:
    com.eden.finance.goldcat.mapper: DEBUG
